# Loading and inspecting a DataFrame

We will use `cities.csv`, stored in the shared `data` folder. Each row represents a Canadian municipality and each column stores an attribute.

In [1]:
import pandas as pd

cities = pd.read_csv("../data/cities.csv")

In [2]:
cities.head()

         Name Prov/terr  Population, 2021  Population, 2016
0  Abbotsford      B.C.          153524.0          141397.0
1     Airdrie     Alta.           74100.0           61581.0
2        Ajax      Ont.          126666.0          119677.0
3        Alma      Que.           30331.0           30771.0
4      Aurora      Ont.           62057.0           55445.0

In [3]:
cities.tail()

             Name Prov/terr  Population, 2021  Population, 2016
174       Windsor      Ont.          229660.0          217188.0
175      Winnipeg      Man.          749607.0          705244.0
176  Wood Buffalo     Alta.           72326.0           71594.0
177     Woodstock      Ont.           46705.0           41098.0
178      Woolwich      Ont.           26999.0           25006.0

In [4]:
cities.shape

(179, 4)

In [5]:
cities.columns

Index(['Name', 'Prov/terr', 'Population, 2021', 'Population, 2016'], dtype='object')

In [6]:
cities.dtypes

Name                 object
Prov/terr            object
Population, 2021    float64
Population, 2016    float64
dtype: object

A pandas table is called a **DataFrame**. Use these inspection commands before attempting to analyze an unfamiliar dataset.