# Filtering rows

In [1]:
import pandas as pd

cities = pd.read_csv("../data/cities.csv")

A comparison applied to a column produces `True` or `False` for every row.

In [2]:
cities["Population, 2021"] >= 100_000

0       True
1      False
2       True
3      False
4      False
       ...
174     True
175     True
176    False
177    False
178    False
Name: Population, 2021, Length: 179, dtype: bool

Use `.loc[]` to retain the rows where the comparison is true.

In [3]:
large_cities = cities.loc[
    cities["Population, 2021"] >= 100_000
]

large_cities.head()

          Name Prov/terr  Population, 2021  Population, 2016
0   Abbotsford      B.C.          153524.0          141397.0
2         Ajax      Ont.          126666.0          119677.0
5       Barrie      Ont.          147829.0          141434.0
11    Brampton      Ont.          656480.0          593638.0
14   Brantford      Ont.          104688.0           98563.0

Text columns can be filtered in the same way.

In [4]:
ontario_cities = cities.loc[
    cities["Prov/terr"] == "Ont."
]

ontario_cities.head()

                         Name Prov/terr  Population, 2021  Population, 2016
2                        Ajax      Ont.          126666.0          119677.0
4                      Aurora      Ont.           62057.0           55445.0
5                      Barrie      Ont.          147829.0          141434.0
6                  Belleville      Ont.           55071.0           50716.0
10  Bradford West Gwillimbury      Ont.           42880.0           35325.0