# Filtering with multiple conditions

In [1]:
import pandas as pd

cities = pd.read_csv("../data/cities.csv")

Use `&` for **and**. Put each pandas condition inside parentheses.

In [2]:
large_ontario_cities = cities.loc[
    (cities["Prov/terr"] == "Ont.")
    & (cities["Population, 2021"] >= 100_000)
]

large_ontario_cities

                                Name  ... Population, 2016
2                               Ajax  ...         119677.0
5                             Barrie  ...         141434.0
11                          Brampton  ...         593638.0
14                         Brantford  ...          98563.0
16                        Burlington  ...         183314.0
20                         Cambridge  ...         129920.0
27                      Chatham-Kent  ...         101647.0
30                               NaN  ...          92013.0
50   Greater Sudbury / Grand Sudbury  ...         161531.0
52                            Guelph  ...         131794.0
56                          Hamilton  ...         536917.0
62                          Kingston  ...         123798.0
63                         Kitchener  ...         233222.0
76                            London  ...         383822.0
81                           Markham  ...         328966.0
84                            Milton  ...         110128.0
87                       Mississauga  ...         721599.0
101                         Oakville  ...         193832.0
105                           Oshawa  ...         159458.0
106                           Ottawa  ...         934243.0
123                    Richmond Hill  ...         195022.0
148                   St. Catharines  ...         133113.0
156                      Thunder Bay  ...         107909.0
158                          Toronto  ...        2731571.0
163                          Vaughan  ...         306233.0
167                         Waterloo  ...         104986.0
171                           Whitby  ...         128377.0
174                          Windsor  ...         217188.0

[28 rows x 4 columns]

Use `|` for **or**.

In [3]:
ontario_or_quebec = cities.loc[
    (cities["Prov/terr"] == "Ont.")
    | (cities["Prov/terr"] == "Que.")
]

ontario_or_quebec.head()

         Name Prov/terr  Population, 2021  Population, 2016
2        Ajax      Ont.          126666.0          119677.0
3        Alma      Que.           30331.0           30771.0
4      Aurora      Ont.           62057.0           55445.0
5      Barrie      Ont.          147829.0          141434.0
6  Belleville      Ont.           55071.0           50716.0

These operators play the same role as `and` and `or` from Week 1, but pandas uses `&` and `|` when comparing whole columns.